### ISSUE TITLE
The Validator Seems Wasteful

### ISSUE THREAD

**Issue by khalidabuhakmeh** [jchannon/netcorecookievalidation#1]
```csharp
public static async Task ValidateAsync(CookieValidatePrincipalContext context)
{
    Console.WriteLine($"VALIDATING {context.Request.Path}");

    //Get user per request
    var user = UserDatabase.GetUser();

    //User has been deleted in the back end so invalidate the cookie
    if (user == null)
    {
        context.RejectPrincipal();
        await context.HttpContext.Authentication.SignOutAsync("MyCookieMW");
        return;
    }

    var claims = new List<Claim>(new[]
    {
        new Claim(ClaimTypes.Name, user.Name),
        new Claim("Age", user.Age.ToString()),
    });

    //Backend user has changed details and differs from cookie so update cookie
    if (!context.Principal.Claims.Select(x => x.Value).SequenceEqual(claims.Select(y => y.Value)))
    {
        Console.WriteLine("UPDATE COOKIE");

        var claimsPrincipal = new ClaimsPrincipal(new ClaimsIdentity(claims, "MyCookieMW"));

        context.ReplacePrincipal(claimsPrincipal);
        context.ShouldRenew = true;
    }
}
```
https://github.com/jchannon/netcorecookievalidation/blob/master/Validator.cs#L12-L43

Calling the `UserDatabase` every time you validate the cookie seems wasteful. A network every time you validate the principal is going to slow down your application.

I would suggest just calling `AuthenticationManager.SignIn` when the user changes any claims stored in the cookie. A call to `SignIn` with an authenticated user results in the current cookie being overwritten by the newer cookie. A user changing their profile will not see a difference in flow, and your application will remain performant.

**Comment by jchannon** [comment]
If that's the case that would the better option. Time to send a PR to the
aspnet docs above?

**Comment by khalidabuhakmeh** [comment]
Where is the link to the ASP.NET Docs?

**Comment by jchannon** [comment]
see "Reacting to back-end changes" https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie

**Comment by jchannon** [comment]
One thing to note is we have a process that updates/deletes our user table from an LDAP system import run every few hours so technically this system could delete a user and that user might still have a valid cookie so we need to check that user exists per request anyway
